### ISSUE TITLE
Not working with 9.81

### ISSUE THREAD

**Issue by smashism** [kitzy/MacDeploymentScripts#1]
I am a sad panda. The jamf binaries have moved so this script no longer works.

**Comment by kitzy** [comment]
Which script specifically? I plan to update all of my scripts but I can make the one you need a priority.

**Comment by smashism** [comment]
Well, none of it works right now. BHT doesn't work in 10.11 and postImageConfig.sh needs the binary location changed.

**Comment by kitzy** [comment]
Ahh, gotcha. I'll update postImageConfig.sh. Unfortunately I didn't write BHT, so I can't update it. I might modify the script to just use JAMF Helper instead. I only used BHT originally due to a bug with JAMF Helper that was resolved ages ago.

**Comment by kitzy** [comment]
I've updated the postImagingConfig.sh script to auto detect the new JAMF binary location, and I removed the BHT dependency. Can you give it a go and see if it works for you?

**Comment by smashism** [comment]
Right now it's not working still. During Casper Imaging the machine reboots after the main Casper Imaging splash logo, but after that it just reboots to the login screen. I checked the config policies and none of them are firing, so it looks like the jamf helper never runs. I'm going to try taking out the check and just running the jamf binary out of the new location directly without the check to see if that makes a difference.

**Comment by kitzy** [comment]
It looks like for some reason it's getting caught up on the check for JSS connection bit. Try pulling out that until loop and see if that works for you. Also try adding a -startLaunchd to the JAMFHelper command. Let me know if that gets you there.

**Comment by smashism** [comment]
I made the changes you recommended and it's still not working. No policies are running on the config trigger. No jamfhelper window. Any other ideas?
